In [436]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
npg= pd.read_csv('data4.csv',header=0)
npg_df = npg.values
npg_arr= np.array(npg_df)
scarler= preprocessing.MinMaxScaler()
npg_arr_minmax=scarler.fit_transform(npg_arr)
x= npg_arr_minmax[:,:2]
y= npg_arr_minmax[:,2:3]


In [475]:
model_mlp = MLPRegressor(solver='lbfgs', hidden_layer_sizes=(8,),activation='relu',max_iter=100)

In [476]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.model_selection import LeaveOneOut

y=y.ravel()
#score=cross_val_score(model_mlp,x,y,cv=5,scoring='neg_mean_squared_error')
cv = LeaveOneOut()
mlp_predict=cross_val_predict(model_mlp,x,y,cv=cv)
#print(np.mean(score))
print ("MSE:",metrics.mean_squared_error(y,mlp_predict))

MSE: 0.00372421917185


In [484]:
d=scarler.inverse_transform(np.column_stack((x,mlp_predict)))
e=scarler.inverse_transform(np.column_stack((x,y)))
#print(d,'\n')
print(e,'\n')
print((e-d)/e,'\n')

print(np.mean(np.abs((e-d)/e),axis=0))
%matplotlib auto
plt.plot(d[:,2])
plt.plot(e[:,2])
plt.xticks(np.arange(1,20,1))

[[  2.70000000e-01   3.30000000e+00   1.36800000e+02]
 [  3.00000000e-01   3.30000000e+00   1.61200000e+02]
 [  3.30000000e-01   3.30000000e+00   1.74400000e+02]
 [  3.60000000e-01   3.30000000e+00   2.34800000e+02]
 [  3.00000000e-01   2.50000000e+00   1.63900000e+02]
 [  3.00000000e-01   2.90000000e+00   1.54000000e+02]
 [  3.00000000e-01   3.30000000e+00   1.61200000e+02]
 [  3.00000000e-01   3.70000000e+00   1.66900000e+02]
 [  3.00000000e-01   4.10000000e+00   1.68600000e+02]
 [  3.00000000e-01   4.90000000e+00   1.40500000e+02]
 [  3.50000000e-01   4.90000000e+00   2.06300000e+02]
 [  4.00000000e-01   4.90000000e+00   2.59800000e+02]
 [  4.50000000e-01   4.90000000e+00   3.32500000e+02]
 [  4.00000000e-01   4.08000000e+00   3.09300000e+02]
 [  4.00000000e-01   4.49000000e+00   2.84100000e+02]
 [  4.00000000e-01   4.90000000e+00   2.59800000e+02]
 [  4.00000000e-01   5.30000000e+00   2.42600000e+02]
 [  4.00000000e-01   5.71000000e+00   2.15100000e+02]] 

[[ 0.          0.        

([<matplotlib.axis.XTick at 0x24e62e7a2e8>,
 <a list of 19 Text xticklabel objects>)